[package]
name = "openwith"
version = "0.1.0"
edition = "2024"

[dependencies]
winreg = "0.55"
windows = { version = "0.61", features = ["Win32_UI_WindowsAndMessaging"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "6.0.0"
